// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use DATABASE_URL from .env or fallback to Docker default
const databaseUrl = process.env["DATABASE_URL"] || "postgresql://lledo:lledo_secret_2024@localhost:5433/lledo_db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
