/**
 * Script de génération de types TypeScript pour les clés i18n
 * Génère des types stricts pour l'autocomplétion et la vérification
 * 
 * Usage: npx ts-node scripts/generate-i18n-types.ts
 */

import * as fs from 'fs'
import * as path from 'path'

const LOCALES_DIR = path.join(__dirname, '../src/i18n/locales/fr')
const OUTPUT_FILE = path.join(__dirname, '../src/types/i18n-keys.d.ts')

function extractKeys(obj: any, prefix = ''): string[] {
  const keys: string[] = []
  
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      keys.push(...extractKeys(value, fullKey))
    } else {
      keys.push(fullKey)
    }
  }
  
  return keys
}

function generateTypes() {
  console.log('\n🔧 Generating i18n types...\n')
  
  // Récupérer tous les namespaces
  const namespaces = fs.readdirSync(LOCALES_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => f.replace('.json', ''))

  let output = `/**
 * Auto-generated i18n types - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-i18n-types.ts
 * Run: npm run i18n:types
 */

`

  // Générer les types pour chaque namespace
  for (const ns of namespaces) {
    const filePath = path.join(LOCALES_DIR, `${ns}.json`)
    const json = JSON.parse(fs.readFileSync(filePath, 'utf-8'))
    const keys = extractKeys(json)
    
    const typeName = ns.charAt(0).toUpperCase() + ns.slice(1) + 'Keys'
    
    console.log(`  📝 ${ns}: ${keys.length} keys -> ${typeName}`)
    
    if (keys.length > 0) {
      output += `export type ${typeName} =\n  | '${keys.join("'\n  | '")}'\n\n`
    } else {
      output += `export type ${typeName} = never\n\n`
    }
  }

  // Générer un type union de tous les namespaces
  output += `// All namespaces\n`
  output += `export type I18nNamespace = ${namespaces.map(ns => `'${ns}'`).join(' | ')}\n\n`

  // Générer un type mapping namespace -> keys
  output += `// Namespace to keys mapping\n`
  output += `export interface I18nKeys {\n`
  for (const ns of namespaces) {
    const typeName = ns.charAt(0).toUpperCase() + ns.slice(1) + 'Keys'
    output += `  ${ns}: ${typeName}\n`
  }
  output += `}\n\n`

  // Helper type pour useTranslation typé
  output += `// Helper for typed useTranslation\n`
  output += `export type TranslationKey<NS extends I18nNamespace> = I18nKeys[NS]\n`

  // Créer le dossier si nécessaire
  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_FILE, output)
  
  console.log(`\n✅ Types generated: ${OUTPUT_FILE}`)
  console.log(`   Total namespaces: ${namespaces.length}`)
}

generateTypes()
